openapi: 3.0.0
info:
  title: Digital Credentialing
  description: "Discussions <a href= \"https://github.com/G2P-Connect/.github/discussions/16\">thread</a> <br><br>
    Manage issuance of digital credential"
  version: 0.1.0
  contact:
    name: G2P Connect
    email: info@g2pconnect.global
  license:
   name: G2P Connect License
   url: 'https://github.com/G2P-Connect/specs/blob/main/LICENSE'
servers:
  - url: https://sandbox.dpg.org/v0.1.0
    description: Sandbox Server

paths:
 /credential/issue:
  post: 
    summary: "CRED-ISSU : /credential/issue"
    description: "Issue credential"
    operationId: post_g2p_cred_issue
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgReqHeader"
                    - properties:
                        action:
                          enum:
                            - issue
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    issue-request:
                      type: array
                      items:
                        $ref: "#/components/schemas/IssueRequest"
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - issue
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /credential/on-issue:
  post: 
    summary: "CRED-ON-ISSU : /credential/on-issue"
    description: "Issuance info through callback"
    operationId: post_g2p_cred_on-issue
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgReqHeader"
                    - properties:
                        action:
                          enum:
                            - on-issue
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    issue-response:
                      type: array
                      items:
                        $ref: "#/components/schemas/IssueResponse"
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - on-issue
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /credential/search:
  post: 
    summary: "CRED-SRCH : /credential/search"
    description: "Credential search request"
    operationId: post_g2p_credential_search
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgReqHeader"
                    - properties:
                        action:
                          enum:
                            - search
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    reference_ids:
                      type: array
                      items:
                        $ref: "#/components/schemas/ReferenceId"
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - status
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
     # - Signature: [ ]
    deprecated: false
 /credential/on-search:
  post: 
    summary: "CRED-ON-SRCH : /credential/on-search"
    description: "Credentail search results through call back"
    operationId: post_g2p_credential_on-search
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackReqHeader"
                    - properties:
                        action:
                          enum:
                            - on-status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    disburse_status:
                      type: array
                      items:
                        $ref: "#/components/schemas/SearchResponse"
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - status'
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /credential/status:
  post: 
    summary: "CRED-STS : /credential/status"
    description: "Credential search request"
    operationId: post_g2p_credential_status
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgReqHeader"
                    - properties:
                        action:
                          enum:
                            - status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    credential_status:
                      type: array
                      items:
                        $ref: "#/components/schemas/StatusRequest"
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - status
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
     # - Signature: [ ]
    deprecated: false
 /credential/on-status:
  post: 
    summary: "CRED-ON-STS : /credential/on-status"
    description: "Credentail status update results through call back"
    operationId: post_g2p_credential_on-status
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackReqHeader"
                    - properties:
                        action:
                          enum:
                            - on-status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    credential_status:
                      type: array
                      items:
                        $ref: "#/components/schemas/StatusResponse"
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - status'
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /credential/txn/status:
  post: 
    summary: "CRED-TXN-STS : /credential/txn/status"
    description: "Polling capability to perform async status check of previous credential transanctions using transaction_id and/or reference_id(s)"
    operationId: post_g2p_credential_txn_status
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgReqHeader"
                    - properties:
                        action:
                          enum:
                            - issue
                            - search
                            - status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    reference_ids:
                      type: array
                      items:
                        $ref: "#/components/schemas/ReferenceId"                          
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - issue
                      - search
                      - status
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /credential/txn/on-status:
  post: 
    summary: "CRED-TXN-ON-STS : /credential/txn/on-status"
    description: "Response to async status check of previous credential transanctions using callback"
    operationId: post_g2p_credential_txn_on-status
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgReqHeader"
                    - properties:
                        action:
                          enum:
                            - on-issue
                            - on-search
                            - on-status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    status-response:
                      type: array
                      items:
                        oneOf:
                        - $ref: "#/components/schemas/IssueResponse"
                        - $ref: "#/components/schemas/SearchResponse"
                        - $ref: "#/components/schemas/StatusResponse"
                      example:
                        status-response: 
                            reference_id: "test"
                            timestamp: "test"
                            status: "SUCC"                        
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - on-issue
                      - on-search
                      - on-status
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
components:
  schemas:
    $ref: "./components/schemas/index.yaml"
  parameters:
    accept-language:
      $ref: "../common/parameter/accept-language.yaml"
    timestamp:
      $ref: "../common/parameter/timestamp.yaml"
    transaction_id:
      $ref: "../common/parameter/transaction_id.yaml"
    summary_only:
      $ref: "../common/parameter/summary_only.yaml"
    beneficiary_id:
      $ref: "../common/parameter/beneficiary_id.yaml"
  responses: 
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"       
    Response:
      $ref: "../common/response/Response.yaml"    
  securitySchemes:
    $ref: "../common/security/index.yaml"