openapi: 3.0.3
info:
  title: Interoperability APIs - Authz
  description: Provide access_token to registered clients/services. Issue OAuth2 compliant authorization token.
  version: 1.0.0
  contact:
    name: G2P Connect 
    email: info@cdpi.dev
  license:
    name: CDPI CC BY-SA 4.0
    url: https://github.com/G2P-Connect/specs/blob/draft/LICENSE.md
externalDocs:
  description: G2P Connect Authorization
  url: https://g2pconnect.cdpi.dev/protocol/security/authorization
servers:
  - url: "https://sandbox.spdci.org/namespace/v1.0.0"
    description: Sandbox Server
paths:
 /oauth2/client/token:
  post: 
    summary: "AUTHZ-TOKN : /oauth2/client/token"
    description: "<br>
      <b>Client integration notes: </b><br>
       1. This end point is in compliance with OAuth2 RFC 6749 to authenticate registered confidential clients with grant_type=client_credentials over HTTPS channel. <br>
       2. Clients MUST obtain client_id, client_secret as part of client registration. <br>
       2. Clients MUST ensure to secure sensitive information e.g, client_secret,  access_token, etc., <br>
       3. RFC 6749 section 4.4.3 recommends NO support for refresh access_token. <br>
       4. Successfully authenticated clients SHALL receive bearer type access_token. <br>
       5. Clients MUST set HTTP \"Authorization: Bearer <access_token>\" in HTTP header to access any g2p compliant api end points.<br>
       6. Rest end points SHALL return <b>http status 401</b> when access_token is invalid or expired.<br>"
    operationId: post_oauth2_client_token
    parameters:
      - $ref: "#/components/parameters/accept-language"
      - $ref: "#/components/parameters/timestamp"
      - $ref: "#/components/parameters/message_id_hdr"
    requestBody:
      description: ""
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/OAuth2ClientTokenRequest"
    responses:
      '200': 
        description: "Acknowledgement of message received after successful validation of message and signature"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OAuth2ClientTokenResponse"
      '404':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
    deprecated: false
components:
  schemas:
    OAuth2ClientTokenRequest:
      $ref: schema/core/OAuth2ClientTokenRequest.yaml
    OAuth2ClientTokenResponse:
      $ref: schema/core/OAuth2ClientTokenResponse.yaml
    OidcScope:
      $ref: schema/core/OidcScope.yaml
  parameters:
    accept-language:
      $ref: "../common/parameter/accept-language.yaml"
    timestamp:
      $ref: "../common/parameter/timestamp.yaml"
    message_id_hdr:
      $ref: "../common/parameter/message_id_hdr.yaml"
  responses:
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"
  securitySchemes:
    x-access-token:
      $ref: "../common/security/x-access-token.yaml"
  