openapi: 3.0.0
info:
  title: Authorization
  description: "Discussions <a href= \"https://github.com/G2P-Connect/.github/discussions\">thread</a> <br><br>
    Provide access_token to registered clients/services. Issue OAuth2 compliant authorization token."
  version: 0.1.0
  contact:
    name: G2P Connect
    email: info@g2pconnect.global
  license:
   name: G2P Connect License
   url: 'https://github.com/G2P-Connect/specs/blob/main/LICENSE'
servers:
  - url: https://sandbox.dpg.org/v0.1.0/{namespace}
    description: Sandbox Server
paths:
 /oauth2/client/token:
  post: 
    summary: "AUTHZ-TOKN : /oauth2/client/token"
    description: "<br>
      <b>Client integration notes: </b><br>
       1. This end point is in compliance with OAuth2 RFC 6749 to authenticate registered confidential clients with grant_type=client_credentials over HTTPS channel. <br>
       2. Clients MUST obtain client_id, client_secret as part of client registration. <br>
       2. Clients MUST ensure to secure sensitive information e.g, client_secret,  access_token, etc., <br>
       3. RFC 6749 section 4.4.3 recommends NO support for refresh access_token. <br>
       4. Successfully authenticated clients SHALL receive bearer type access_token. <br>
       5. Clients MUST set access_token to x-access-token in HTTP header to access any g2p compliant api end points.<br>
       6. Rest end points SHALL return <b>http status 401</b> when access_token is invalid or expired.<br>"
    operationId: post_oauth2_client_token
    parameters:
      - $ref: "#/components/parameters/accept-language"
      - $ref: "#/components/parameters/timestamp"
      - $ref: "#/components/parameters/message_id_hdr"
    requestBody:
      description: ""
      required: true
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/OAuth2ClientTokenRequest"
    responses:
      '200': 
        description: "Acknowledgement of message received after successful validation of message and signature"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OAuth2ClientTokenResponse"
      '404':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    deprecated: false
components:
  schemas:
    $ref: "./components/schemas/index.yaml"
  parameters:
    accept-language:
      $ref: "../common/parameter/accept-language.yaml"
    timestamp:
      $ref: "../common/parameter/timestamp.yaml"
    message_id_hdr:
      $ref: "../common/parameter/message_id_hdr.yaml"
  responses:
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"        