openapi: 3.0.0
info:
  title: Identity
  description: "Discussions <a href= \"https://github.com/G2P-Connect/.github/discussions/16\">thread</a> <br><br>
    Manage issuance of digital credential"
  version: 0.1.0
  contact:
    name: G2P Connect
    email: info@g2pconnect.global
  license:
   name: G2P Connect License
   url: 'https://github.com/G2P-Connect/specs/blob/main/LICENSE'
servers:
  - url: https://sandbox.dpg.org/v0.1.0
    description: Sandbox Server

paths:
 /identity/verify:
  post: 
    summary: "ID-VRFY : /identity/verify"
    description: "Verification of person's demographics against foundational id"
    operationId: post_g2p_id_verify
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - issue
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    verify_request:
                      type: array
                      items:
                        $ref: "#/components/schemas/VerifyRequest"
                  required:
                    - transaction_id
                    - verify_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - issue
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /credential/on-issue:
  post: 
    summary: "ID-ON-VRFY : /idenity/on-issue"
    description: "Verification response through callback"
    operationId: post_g2p_id_on-verify
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - on-issue
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    verify_response:
                      type: array
                      items:
                        $ref: "#/components/schemas/VerifyResponse"
                  required:
                    - transaction_id
                    - verify_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - on-issue
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /credential/txn/status:
  post: 
    summary: "ID-TXNSTS : /identity/txn/status"
    description: "Perform async status check of previous identity transanctions using transaction_id and/or reference_id(s)"
    operationId: post_g2p_id_txnstatus
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - issue
                            - search
                            - status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    txnstatus_request:
                      $ref: "#/components/schemas/TxnStatusRequest"
                  required:
                    - transaction_id
                    - txnstatus_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - issue
                      - search
                      - status
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /identity/txn/on-status:
  post: 
    summary: "ID-ON-TXNSTS : /identity/txn/on-status"
    description: "Response to async status check of previous identity transanctions using callback"
    operationId: post_g2p_id_on-txnstatus
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - on-issue
                            - on-search
                            - on-status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    txnstatus_response:
                      $ref: "#/components/schemas/TxnStatusResponse"
                  required:
                    - transaction_id
                    - txnstatus_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - on-issue
                      - on-search
                      - on-status
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
components:
  schemas:
    $ref: "./components/schemas/index.yaml"
  parameters:
    accept-language:
      $ref: "../common/parameter/accept-language.yaml"
    timestamp:
      $ref: "../common/parameter/timestamp.yaml"
    transaction_id:
      $ref: "../common/parameter/transaction_id.yaml"
    summary_only:
      $ref: "../common/parameter/summary_only.yaml"
    beneficiary_id:
      $ref: "../common/parameter/beneficiary_id.yaml"
  responses: 
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"       
    Response:
      $ref: "../common/response/Response.yaml"    
  securitySchemes:
    $ref: "../common/security/index.yaml"