openapi: 3.0.0
info:
  title: Disbursement
  description: "Discussions <a href= \"https://github.com/G2P-Connect/.github/discussions/15\">thread</a> <br><br>
    Social protection platform initiating G2P disbursements. Supports api, events and file based messaging"
  version: 0.1.0
  contact:
    name: G2P Connect
    email: info@g2pconnect.global
  license:
   name: G2P Connect License
   url: 'https://github.com/G2P-Connect/specs/blob/main/LICENSE'
servers:
  - url: https://sandbox.dpg.org/v0.1.0
    description: Sandbox Server
paths:
 /disburse:
  post: 
    summary: "DSBT-DSBT : /disburse"
    description: "Initiate payment through disbursement instructions"
    operationId: post_g2p_dsbt_disburse
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - disburse
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    disburse_request:
                      type: array
                      items:
                        $ref: "#/components/schemas/DisburseRequest"
                  required:
                    - transaction_id
                    - disburse_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - disburse
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /on-disburse:
  post: 
    summary: "DSBT-ON-DSBT : /on-disburse"
    description: "The callback is called by /disburse end point processing systems upon completing all disbursement instructions"
    operationId: post_g2p_dsbt_on-disburse
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - on-disburse
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    disburse_response:
                      type: array
                      items:
                        $ref: "#/components/schemas/DisburseResponse"
                  required:
                    - transaction_id
                    - disburse_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - on-disburse
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /disburse/search:
  post: 
    summary: "DSBT-SRCH : /disbruse/search"
    description: "Search disbursement by searchable attributes"
    operationId: post_g2p_dsbt_search
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - search
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    search_request:
                      $ref: "#/components/schemas/SearchRequest"
                  required:
                    - transaction_id
                    - search_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - search
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
     # - Signature: [ ]
    deprecated: false
 /disburse/on-search:
  post: 
    summary: "DSBT-ON-SRCH : /credential/on-search"
    description: "Disbrusement search results through call back"
    operationId: post_g2p_dsbt_on-search
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - on-search
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    search_response:
                      type: array
                      items:
                        $ref: "#/components/schemas/SearchResponse"
                  required:
                    - transaction_id
                    - search_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - on-search'
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /disburse/txn/status:
  post: 
    summary: "DSBT-TXNSTS : /disburse/txn/status"
    description: "Perform async status check of previous disbursement transanctions using searchable attributes"
    operationId: post_g2p_dsbt_txnstatus
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    txnstatus_request:
                      $ref: "#/components/schemas/TxnStatusRequest"
                  required:
                    - transaction_id
                    - txnstatus_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - status
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
     # - Signature: [ ]
    deprecated: false
 /disburse/txn/on-status:
  post: 
    summary: "DSBT-ON-TXNSTS : /disburse/txn/on-status"
    description: "Response to async status check of previous disbursement transanctions using callback"
    operationId: post_g2p_dsbt_on-txnstatus
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - on-status
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    txnstatus_response:
                      type: array
                      items:
                        $ref: "#/components/schemas/TxnStatusResponse"
                  required:
                    - transaction_id
                    - txnstatus_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - status'
    responses:
      default:
        $ref: "#/components/responses/Response"
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /disburse/search/{transaction_id}/{summary_only}:
   get: 
    summary: "DSBT-SRCH-TXNID: /disburse/search/{transaction_id}/{summary_only}"
    description: "Get disbursement processing status by polling <br>
        1. This end point is avaiable to poll disbursement processing status info. <br>
        2. It is recommended to fetch with default summay_only flag to reduce load on the systems. <br>
        3. Disbursement processing systems may chose to implement rate limiting at transaction_id level to avoid request flooding."
    operationId: get_g2p_dsbt_search_by_txn_id
    parameters:
      - $ref: "#/components/parameters/accept-language"
      - $ref: "#/components/parameters/timestamp"
      - $ref: "#/components/parameters/transaction_id"
      - $ref: "#/components/parameters/summary_only"
    responses:
      default:
        description: "Acknowledgement of message received after successful validation of message and signature"
        content:
          application/json:
            schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - search
                message:
                  type: object                    
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    disburse_response:
                      type: array
                      items:
                        $ref: "#/components/schemas/DisburseResponse"
                  required:
                    - transaction_id
                    - disburse_response
              required:
                - header
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /disburse/search/{reference_id}:
   get: 
    summary: "DSBT-SRCH-REFID : /disburse/search/{reference_id}"
    description: "Get disbursement processing status by polling using reference_id <br>
        1. This end point is avaiable to poll disbursement processing status info. <br>
        2. Disbursement processing systems may chose to implement rate limiting at reference_id level to avoid request flooding."
    operationId: get_g2p_dsbt_search_by_ref_id
    parameters:
      - $ref: "#/components/parameters/accept-language"
      - $ref: "#/components/parameters/timestamp"
      - $ref: "#/components/parameters/reference_id"
    responses:
      default:
        description: "Acknowledgement of message received after successful validation of message and signature"
        content:
          application/json:
            schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - search
                message:
                  type: object                    
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    disburse_response:
                      type: array
                      items:
                        $ref: "#/components/schemas/DisburseResponse"
                  required:
                    - transaction_id
                    - disburse_response
              required:
                - header
      '401':
        $ref: "#/components/responses/HttpErrorResponse"
      '403':
        $ref: "#/components/responses/HttpErrorResponse"
      '500':
        $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
     # - Signature: [ ]
    deprecated: false
components:
  schemas:
    $ref: "./components/schemas/index.yaml"
  parameters:
    accept-language:
      $ref: "../common/parameter/accept-language.yaml"
    timestamp:
      $ref: "../common/parameter/timestamp.yaml"
    transaction_id:
      $ref: "../common/parameter/transaction_id.yaml"
    summary_only:
      $ref: "../common/parameter/summary_only.yaml"
    reference_id:
      $ref: "../common/parameter/reference_id.yaml"
  responses:
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"    
    Response:
      $ref: "../common/response/Response.yaml"    
  securitySchemes:
    $ref: "../common/security/index.yaml"