openapi: 3.0.0
info:
  title: Civil Registry
  description: "Discussions <a href= \"https://github.com/G2P-Connect/.github/discussions/16\">thread</a> <br><br>
    Manage issuance of digital credential"
  version: 0.1.0
  contact:
    name: G2P Connect
    email: info@g2pconnect.global
  license:
   name: G2P Connect License
   url: 'https://github.com/G2P-Connect/specs/blob/main/LICENSE'
servers:
  - url: https://sandbox.dpg.org/{namespace}/v0.1.0 
    description: Sandbox Server
paths:
 /registry/search:
  post: 
    summary: "REG-SRCH : /registry/search"
    description: "Search person(s) in registry using key identifiers"
    operationId: post_g2p_registry_search
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - search
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    search_request:
                      type: array
                      items:
                        $ref: "#/components/schemas/SearchRequest"
                  required:
                    - transaction_id
                    - search_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - search
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /registry/on-search:
  post: 
    summary: "REG-ON-SRCH : /registry/on-search"
    description: "Search results through callback"
    operationId: post_g2p_registry_on-search
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - on-search
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    search_response:
                      type: array
                      items:
                        $ref: "#/components/schemas/SearchResponse"
                  required:
                    - transaction_id
                    - search_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - on-search
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /registry/subscribe:
  post: 
    summary: "REG-SUB : /registry/subscribe"
    description: "Subscribe to a life event with registry"
    operationId: post_g2p_registry_subscribe
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - subscribe
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    subscribe_request:
                      type: array
                      items:
                        $ref: "#/components/schemas/SubscribeRequest"
                  required:
                    - transaction_id
                    - subscribe_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - subscribe
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /registry/notify:
  post: 
    summary: "REG-NTFY : /registry/notify"
    description: "Registry to notify a life event to subscrbiers"
    operationId: post_g2p_registry_notify
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - notify
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    notify_event:
                      type: array
                      items:
                        $ref: "#/components/schemas/NotifyEventRequest"
                  required:
                    - transaction_id
                    - verify_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - notify
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /registry/txn/status:
  post: 
    summary: "REG-TXNSTS : /registry/txn/status"
    description: "Perform async status check of previous civil registry transanctions using transaction_id and/or reference_id(s)"
    operationId: post_g2p_id_txnstatus
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgHeader"
                    - properties:
                        action:
                          enum:
                            - subscribe
                            - notify
                            - on-search
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    txnstatus_request:
                      $ref: "#/components/schemas/TxnStatusRequest"
                  required:
                    - transaction_id
                    - txnstatus_request
              required:
                - header
                - message
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - subscribe
                      - notify
                      - on-search
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
 /identity/txn/on-status:
  post: 
    summary: "REG-ON-TXNSTS : /registry/txn/on-status"
    description: "Response to async status check of previous civil registrt transanctions using callback"
    operationId: post_g2p_registry_on-txnstatus
    requestBody:
      description: ""
      required: true
      content:
        application/json:
          schema:
              type: object
              properties:
                signature:  
                  $ref: "#/components/schemas/MsgSignature"
                header:
                  allOf:
                    - $ref: "#/components/schemas/MsgCallbackHeader"
                    - properties:
                        action:
                          enum:
                            - subscribe
                            - notify
                            - on-search
                message:
                  type: object
                  properties:
                    transaction_id: 
                      $ref: "#/components/schemas/TransactionId"
                    txnstatus_response:
                      $ref: "#/components/schemas/TxnStatusResponse"
                  required:
                    - transaction_id
                    - txnstatus_response
              required:
                - header
        multipart/form-data:
          schema:
            allOf:
              - $ref: "#/components/schemas/FileInfo"
              - properties:
                  action:
                    enum:
                      - subscribe
                      - notify
                      - on-search
    responses:
        default:
          $ref: "#/components/responses/Response"
        '401':
          $ref: "#/components/responses/HttpErrorResponse"
        '403':
          $ref: "#/components/responses/HttpErrorResponse"
        '500':
          $ref: "#/components/responses/HttpErrorResponse"
    security:
      - x-access-token: [ ]
      # - Signature: [ ]
    deprecated: false
components:
  schemas:
    $ref: "./components/schemas/index.yaml"
  parameters:
    accept-language:
      $ref: "../common/parameter/accept-language.yaml"
    timestamp:
      $ref: "../common/parameter/timestamp.yaml"
    transaction_id:
      $ref: "../common/parameter/transaction_id.yaml"
    summary_only:
      $ref: "../common/parameter/summary_only.yaml"
    beneficiary_id:
      $ref: "../common/parameter/beneficiary_id.yaml"
  responses: 
    HttpErrorResponse:
      $ref: "../common/response/HttpErrorResponse.yaml"       
    Response:
      $ref: "../common/response/Response.yaml"    
  securitySchemes:
    $ref: "../common/security/index.yaml"