openapi: 3.0.0
info:
  title: G2P Connect Payment Definitions
  description: G2P Connect scehmas to interface between social protection systems, payment rails. This is an adaptation of G2P Connect core version 0.1.0
  version: 0.1.0
  contact:
    name: G2P Connect
    email: info@g2pconnect.global
paths: {}
components:
  schemas:
    Payments:
      description: 'Payment list as a collection for bulk processing'
      type: array
      items:
        $ref: '#/components/schemas/Payment'
    PaymentsStatus:
      description: 'Payments status list as a collection for bulk processing'
      type: array
      items:
        $ref: '#/components/schemas/PaymentStatus'
    Payment:
      description: "Describes payment schema that enable transfer from payer to payee accounts. This entity supports immediate and scheduling one time payment request into future. Recurring payments is not part of the scope of this entity."
      type: object
      properties:
        locale:
          $ref: "#/components/schemas/LanguageCode"
        request_id:
          description: 'Unique uuid set by social protect sytem while initiating the payment'
          type: string
        request_datetime: 
          description: 'Payment initiation request data time in ISO 8601 format. All date-time fields must include the timezone. An example is below:'
          type: string
          format: date-time
          example: '2022-12-04T18:01:07+00:00'
        scheduled_datetime: 
          description: 'For immediate payments, scheduled_datetime can be same as request_datetime and a valid ISO 8601 format datetime for schedule the payment into future. An example is below.'
          type: string
          format: date-time
          example: '2022-12-04T18:01:07+00:00'
        payer:
          description: "Payer defined in a normative format - AccountIdentifierType:AccountIdentifier that enable to identify end payer's FSP and account."
          type: string
          example: account:1234567890@bank-code
        payee:
          description: 'Payee defined in a normative format - AccountIdentifierType:AccountIdentifier that enable to identify end beneficary Financial Service Provider (FSP) and Account.'
          type: string
          example: mosip:2356441678
        amount:
          $ref: '#/components/schemas/Amount'
        currency:
          $ref: '#/components/schemas/CurrencyCode'
        info:
          description: "Info to payer/payee."
          type: string
          maxLength: 40
        scheme_code:
          description: "G2P social protection system defined scheme short code for easy reference. Available as master reference data."
          type: string
          maxLength: 40  
        additional_info:
          description: "Additional info for interfacing DPGs platforms to integrate, reconcile, etc., unstructured data."
          type: string
          maxLength: 1024
      required:
        - locale
        - request_id
        - date
        - payer
        - payee
        - amount
        - currency
    PaymentStatus:
      description: Describes payment status schema to social protection system for tracking and reconcilation.
      type: object
      properties:
        locale:
          $ref: "#/components/schemas/LanguageCode"
        reference_code:
          description: 'Unique uuid set by social protect sytem while initiating the payment'
          type: string
        request_id:
          description: 'Unique uuid set by social protect sytem while initiating the payment'
          type: string
        datetime: 
          description: 'Payment processing data time in ISO 8601 format. All date-time fields must include the timezone. An example is below:'
          type: string
          format: date-time
          example: '2022-12-04T18:01:07+00:00'
        payer:
          description: ''
          type: string
        payee:
          description: ''
          type: string
        amount:
          $ref: '#/components/schemas/Amount'
        currency:
          $ref: '#/components/schemas/CurrencyCode'
        status:
          description: 'Payment processing status to enable integrating DPGs to track and reconcile payments.'
          type: string
          enum: 
            - Pending
            - Rejected
            - AcceptedSettlementInProcess
            - AcceptedSettlementCompleted
            - AcceptedWithoutPosting
            - AcceptedCreditSettlementCompleted
        error_code:
          description: 'Additional error codes'
        error_message:
          description: 'Additional error messages'
        additional_info:
          description: "Additional info for interfacing DPGs platforms to integrate, reconcile, etc., unstructured data."
          type: string
          maxLength: 1024
      required:
        - locale
        - reference_code
        - request_id
        - datetime
        - payer
        - payee
        - amount
        - currency
        - status
    AccountIdentifierType:
      description: "Defined list of account identifier types to identify payer and payee account types. Country specific implemenation list shall be defined as a network policy."
      type: string
      example:  [account, email, msisdn, mosip, aadhaar, upi] 
    AccountIdentifier:
      description: "Identifier issued by the account identifier system to locate payer and payee accounts."
      type: string
      example:  [1234567890@bank-code, john.doe@gmail.com, 9876543210@MobileMoney, 2356441678, 436738651254, john@sbi] 
    CurrencyCode:
      description: Currency code allocated as per ISO 4217 format; Codes for the representation of currencies and funds.
      type: string
      pattern: '^[A-Z]{3,3}$'
      example: "SLL"
    Amount:
      description: Describes amount in decimal value format
      type: string
      pattern: '^\d{1,13}\.\d{1,2}$'
    LanguageCode:
      description: indicates language code. G2P Connect supports country codes as per ISO 639.3 standard
      type: string   
      pattern: '^[a-z]{3,3}$'
      example: "kri"