type: object
description: |
  @context: https://schema.spdci.org/common/v1/api-schemas/Meta.jsonld <br>
  @type: "@context" <br>
    
  **Notes:**
    1. Additional meta info defined as per implementation context.
    2. Usually unencrypted list of name/value, tags, etc., to provide additional info to intermediary entities.
    3. The information SHOULD be privacy preserving