type: object
description: |
  @context: "https://example.org/schema/Meta" <br>
  @type: "@context" <br>
    
  **Notes:**
    1. Additional meta info defined as per implementation context.
    2. Usually list of name/value, tags, etc., to provide additional info.
    3. The information SHOULD be privacy preserving attributes/values when passed in the protocol header.